### ISSUE TITLE
Moz Mercurial infra repositories

### ISSUE THREAD

**Issue by Akhliskun** [Akhliskun/firefox-infra-changelog#2]
We will need to create a list of all mercurial repositories that are being used for firefox-ci and/or could influence the infra. 

A good place to start would be our team's Google Drive Escalation Doc. 

Please post in the following format:
`<Name of repo> - <Link to mercurial repo>`

**Comment by zsoltfay** [comment]
These are the candidates so far:

https://hg.mozilla.org/hgcustom/hghooks/
https://hg.mozilla.org/hgcustom/hgscripts/
https://hg.mozilla.org/hgcustom/version-control-tools/
https://hg.mozilla.org/hgcustom/hg_templates/
https://hg.mozilla.org/mozilla-build/
https://hg.mozilla.org/build/buildapi/
https://hg.mozilla.org/build/braindump/
https://hg.mozilla.org/build/mozharness/
https://hg.mozilla.org/build/tooltool/
https://hg.mozilla.org/build/slave_health/
https://hg.mozilla.org/build/puppet-manifests/
https://hg.mozilla.org/build/cloud-tools/
https://hg.mozilla.org/build/ci-configuration/
https://hg.mozilla.org/build/ci-admin/
https://hg.mozilla.org/build/nagios-tools/

**Comment by Akhliskun** [comment]
Hey guys, is this still applicable? 
Are the repositories listed here the ones that we need?

**Comment by bccrisan** [comment]
Yes it is

**Comment by bccrisan** [comment]
This seems to be the complete list so far.
* Version Control Tools - https://hg.mozilla.org/hgcustom/version-control-tools/
* Mozilla Build - https://hg.mozilla.org/mozilla-build/
* Mozilla Central - https://hg.mozilla.org/mozilla-central/
* Try - https://hg.mozilla.org/try/
* Autoland - https://hg.mozilla.org/integration/autoland/
* Inbound - https://hg.mozilla.org/integration/mozilla-inbound/
* comm-esr60 - https://hg.mozilla.org/releases/comm-esr60/
* Beta - https://hg.mozilla.org/releases/mozilla-beta/
* mozilla-esr60 - https://hg.mozilla.org/releases/mozilla-esr60/
* mozilla-release - https://hg.mozilla.org/releases/mozilla-release/
* braindump - https://hg.mozilla.org/build/braindump/
* mozharness - https://hg.mozilla.org/build/mozharness/
* CI Configuration - https://hg.mozilla.org/build/ci-configuration/
* CI Admin - https://hg.mozilla.org/build/ci-admin/

**Comment by bccrisan** [comment]
Added in PR #46

**Comment by bccrisan** [comment]
This is done, nothing to do here.
