### ISSUE TITLE
Ignore the special characters ( UTF-8 encoding)

### ISSUE THREAD

**Issue by raduiman** [Akhliskun/firefox-infra-changelog#22]
## Short description:
If a commit message contain a special character like '\n' for new line or '\r' carriage return or '\t' tab ...( #, """, \, %, etc), it will affect our files (Json and MD)

## Where to start:
We have two option to fix this:
Option 1:  We have to encode the information using UTF-8 witch will interpret those characters as a string so our .json and .md will not be affected
Option 2:  We have to remove those characters from text to make it more clean and easy to read

## Requirements
* Don't use classes
* Runs on Py3.X
* Document the code

## What we have until now:
First option:  we can encode each information using ".encode("utf-8")"  after we get it from API
Option two: we can import 're' library and use  "re.sub" function to remove the characters from the string

Any better idea will be welcome.

**Comment by Akhliskun** [comment]
A good example on how to achieve this is following @mutterroland 's example here:
[PROPOSED PR](https://github.com/Akhliskun/firefox-infra-changelog/pull/35/files#diff-2d5864fe4ab14d4494a119b54f63c3cfR103)

Basically we can substitute parts of strings. But going with UTF-8 encoding also makes sense as this will be a "catch them all" aproach, where using re.sub will require us to make handlers for each case.

**Comment by zsoltfay** [comment]
This has been implemented and the commit message inside the markdown files causes no issues and it's displayed flawlessly.
