### ISSUE TITLE
Idea to have a list with all the files which affect CI

### ISSUE THREAD

**Issue by raduiman** [Akhliskun/firefox-infra-changelog#23]
**Short description**
We can figure out if a change affects CI by checking if this change happened in one of the CI files. 

**First solution**
After we have a list with all the CI files we can check if the affected file is in our list, if it is we can save those changes if not we can ignore them.

**First step**
We can start to create a list with all the CI files

**Proposal**
1.  Should we make a list for each repository separately or all in one? My thought is to have one separately for each repository, so we'll can compare the affected files from current repository with his CI-files list instead with a very large list.

**Comment by lundjordan** [comment]
yep, each repository separately makes sense. I think. This is similar to https://github.com/Akhliskun/firefox-infra-changelog/issues/41 so perhaps they should be merged?

**Comment by raduiman** [comment]
Similar to #41.
