### ISSUE TITLE
def filter_commit_data(commit) breaks generated markdown file

### ISSUE THREAD

**Issue by mutterroland** [Akhliskun/firefox-infra-changelog#34]
def filter_commit_data(commit) currently breaks generated markdown file. 
Will modify the function for a workaround.

Example: 
## SHIP-IT MARKDOWN TABLE

| Commit Number | Commiter | Commit Message | Date |
|:---:|:----:|:----------------------------------:|:----:| 
|1|Patrick Cloke|Bump Thunderbird to version 65. (#239)|2018-10-29T22:40:41Z
|2|Rob Lemley|Bug 1502445 - Remove obsolete locales from Thunderbird. (#241)

The downloads page on thunderbird.net uses thunderbird_primary_builds.json

to generate the download list. There's some locales included there

that have been removed from Thunderbird in bug 1310221. This patch

brings thunderbirddetails.py (mostly) inline with all-locales in

comm/mail/locales.|2018-10-29T22:30:04Z
|3|Rail Aliiev|Use raw string for regexes (#242)|2018-10-29T22:22:50Z
|4|Pascal Chevrel|Nightly 65: Merge and deply when 65 builds are available for all locales (#238)|2018-10-23T09:27:10Z
|5|Nick Thomas|Use N most recent releases only (#237)|2018-10-17T20:10:15Z
|6|Pascal Chevrel|Update false Fennec instructions in template (#236)|2018-09-10T16:20:59Z
|7|Patrick Cloke|Bump Thunderbird nightly version to 64. (#234)|2018-09-05T14:40:36Z
|8|Pascal Chevrel|Update available firefox nightly version to 64. (#233)|2018-09-05T14:28:27Z
|9|Julien Cristau|Bug 1460752 - bump CURRENT_ESR to 60 (#235)|2018-09-05T13:27:57Z
|10|Rail Aliiev|Reformat, add more info (#232)|2018-07-13T20:49:08Z
|11|Rail Aliiev|Handle "legacy" releases properly, kill python2.6 (#231)

**Comment by mutterroland** [comment]
This is how it looks after the fix : 
## SHIP-IT MARKDOWN TABLE

| Commit Number | Commiter | Commit Message | Date |
|:---:|:----:|:----------------------------------:|:----:|
|1|Patrick Cloke|Bump Thunderbird to version 65. (#239)|2018-10-29T22:40:41Z
|2|Rob Lemley|Bug 1502445 - Remove obsolete locales from Thunderbird. (#241)  The downloads page on thunderbird.net uses thunderbird_primary_builds.json  to generate the download list. There's some locales included there  that have been removed from Thunderbird in bug 1310221. This patch  brings thunderbirddetails.py (mostly) inline with all-locales in  comm/mail/locales.|2018-10-29T22:30:04Z
|3|Rail Aliiev|Use raw string for regexes (#242)|2018-10-29T22:22:50Z
|4|Pascal Chevrel|Nightly 65: Merge and deply when 65 builds are available for all locales (#238)|2018-10-23T09:27:10Z
|5|Nick Thomas|Use N most recent releases only (#237)|2018-10-17T20:10:15Z
|6|Pascal Chevrel|Update false Fennec instructions in template (#236)|2018-09-10T16:20:59Z
|7|Patrick Cloke|Bump Thunderbird nightly version to 64. (#234)|2018-09-05T14:40:36Z
|8|Pascal Chevrel|Update available firefox nightly version to 64. (#233)|2018-09-05T14:28:27Z
|9|Julien Cristau|Bug 1460752 - bump CURRENT_ESR to 60 (#235)|2018-09-05T13:27:57Z
|10|Rail Aliiev|Reformat, add more info (#232)|2018-07-13T20:49:08Z
|11|Rail Aliiev|Handle "legacy" releases properly, kill python2.6 (#231)    Add "legacy" release      Break the tests      Do not return flask.Response object for legacy        When a release uses l10nChangesets: "legacy" (not available?), the      corresponding function (_getReleaseLocales) returns a flask.Response      object (generated by jsonify_by_sorting_values). This breaks the logic      when we export aggregated (combined betas) release JSON files, because      flask.Response is not JSON serializable.|2018-07-11T02:19:18Z
|12|Rail Aliiev|Deployment info (#230)|2018-07-10T15:44:51Z
|13|Rail Aliiev|Add deployment section (#229)|2018-07-10T14:06:41Z
|14|Rail Aliiev|Set iOS versions (#228)|2018-06-27T09:47:07Z

**Comment by Akhliskun** [comment]
I think it would be better to display the date-time like this:
`2018-09-10 16:20:59`

(remove the T and Z from the string)

**Comment by mutterroland** [comment]
I think this is the perfect candidate for a new issue . Moving to issue #43
