### ISSUE TITLE
Create a main markdown table

### ISSUE THREAD

**Issue by mutterroland** [Akhliskun/firefox-infra-changelog#45]
Opening this feature request as I would like to suggest creating a main markdown table containing information such as one listed below:
What's your opinion on this?

## MARKDOWN MAIN TABLE

| Repo | Link | Last Message | Data |
|:---:|:----:|:----------------------------------:|:----:|
|<a href=https://github.com/mozilla-releng/ship-it>ship-it</a>|<a href="file:///C:\Users\roland.mutter\Desktop\FireFox ChangeLog\firefox-infra-changelog\tests\ship-it.md">link</a>|Nightly 65: Merge and deply when 65 builds are available for all locales (#238)|2018-10-23T09:27:10Z
|<a href=https://github.com/mozilla/release-services>release-services</a>|<a href="file:///C:\Users\roland.mutter\Desktop\FireFox ChangeLog\firefox-infra-changelog\tests\release-services.md">link</a>|staticanalysis/frontend: Load all tasks & support http errors (#1651)|2018-10-26T09:44:46Z
|<a href=https://github.com/mozilla-releng/beetmoverscript>beetmoverscript</a>|<a href="file:///C:\Users\roland.mutter\Desktop\FireFox ChangeLog\firefox-infra-changelog\tests\beetmoverscript.md">link</a>|Bug 1408083 - Drop support for beta/releases of single locale repacks for Fennec (#187)|2018-10-03T10:31:17Z
|<a href=https://github.com/mozilla-releng/addonscript>addonscript</a>|<a href="file:///C:\Users\roland.mutter\Desktop\FireFox ChangeLog\firefox-infra-changelog\tests\addonscript.md">link</a>|Merge pull request #96 from mozilla-releng/pyup-update-scriptworker-14.0.0-to-15.0.0  Update scriptworker to 15.0.0|2018-08-06T02:31:08Z
|<a href=https://github.com/mozilla-releng/shipit-v2>shipit-v2</a>|<a href="file:///C:\Users\roland.mutter\Desktop\FireFox ChangeLog\firefox-infra-changelog\tests\shipit-v2.md">link</a>|RM ALL|2018-09-06T19:59:08Z
|<a href=https://github.com/mozilla-releng/build-cloud-tools>build-cloud-tools</a>|<a href="file:///C:\Users\roland.mutter\Desktop\FireFox ChangeLog\firefox-infra-changelog\tests\build-cloud-tools.md">link</a>|Merge pull request #368 from garbas/remove-uplift-frontend  terraform: remove uplift frontend domains|2018-10-23T14:44:31Z
|<a href=https://github.com/mozilla-releng/build-puppet>build-puppet</a>|<a href="file:///C:\Users\roland.mutter\Desktop\FireFox ChangeLog\firefox-infra-changelog\tests\build-puppet.md">link</a>|Bug 1481203 - allow worker to use new thunderbird ship-it scopes (#278)  The release-mark-as-shipped task for Thunderbird has new scopes  assigned to it. This patch updates the scriptworker configuration  to recognize those scopes, preventing the 'This worker is not configured  to handle scope "project:comm:thunderbird:releng:ship-it:server:production"'  error when run.|2018-10-26T20:11:29Z
|<a href=https://github.com/mozilla-releng/shipitscript>shipitscript</a>|<a href="file:///C:\Users\roland.mutter\Desktop\FireFox ChangeLog\firefox-infra-changelog\tests\shipitscript.md">link</a>|Merge pull request #13 from escapewindow/py37  require py37 to be green|2018-07-27T23:05:59Z
|<a href=https://github.com/mozilla-releng/bouncerscript>bouncerscript</a>|<a href="file:///C:\Users\roland.mutter\Desktop\FireFox ChangeLog\firefox-infra-changelog\tests\bouncerscript.md">link</a>|Merge pull request #41 from tp-tc/stub-path-platforms   Check that paths exist per-platform.|2018-09-04T22:05:15Z
|<a href=https://github.com/mozilla-releng/treescript>treescript</a>|<a href="file:///C:\Users\roland.mutter\Desktop\FireFox ChangeLog\firefox-infra-changelog\tests\treescript.md">link</a>|Merge pull request #111 from tp-tc/bump-robustcheckout.py  Bump robustcheckout.py.|2018-10-02T16:43:57Z
|<a href=https://github.com/mozilla-releng/mozapkpublisher>mozapkpublisher</a>|<a href="file:///C:\Users\roland.mutter\Desktop\FireFox ChangeLog\firefox-infra-changelog\tests\mozapkpublisher.md">link</a>|0.9.0|2018-10-19T12:42:47Z

**Comment by mutterroland** [comment]
For this to work, we need at least one set of generated md tables for each repo (for the hyperlink hidden in repo name to work) and at least one set of changelog.json for every repo.

**Comment by bccrisan** [comment]
As discussed in the last CIDuty Staff Meeting, this should be considered a priority.

Looking into the table, the link column should be a link to what? the last commit in that repository? 
Also what will also be useful is to limit the description to.. let's say 2-3 rows or something similar. 
The idea is not to have like 10 rows like build-puppet has in your example.
Also, keep in mind that here the table looks pretty narrow. In a real-world use case, the "Last Message" column would probably be larger.

There is space to experiment.

**Comment by zsoltfay** [comment]
I can see what roland said happening, but for this we would need:
1. a def to dump the data of each repo into a separate .json file
2. another def which creates the markdown
If you guys think it's a good idea we can work on this after we sort out issue #50

**Comment by bccrisan** [comment]
That would be issue #51 that you are talking about

**Comment by bccrisan** [comment]
Currently working in a remote repository - https://github.com/bccrisan/create_main_mk_table/

**Comment by raduiman** [comment]
Merged PR #83  Added main markdown table.
