### ISSUE TITLE
No commit message available while filtering git commit data

### ISSUE THREAD

**Issue by bccrisan** [Akhliskun/firefox-infra-changelog#50]
**Describe the bug**
After adding all of the github repositories to `repositories.json`, the script started throwing the following error
`
Traceback (most recent call last):
  File "E:/bcrisan/repos/fic/client.py", line 186, in <module>
    useful_data = filter_commit_data(commit_data)
  File "E:/bcrisan/repos/fic/client.py", line 151, in filter_commit_data
    commit_message = item['commit']['message']
TypeError: string indices must be integers
`

**To Reproduce**
1. Open the project in pycharm
2. Clone the project
3. Make sure you have the GIT_TOKEN installed
4. Run the script
5. See error

**Expected behavior**
The creation of multiple `.md` that would contain the commits table for each repository newly added under github json.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Not applicable 
- Version: any version that contains commit https://github.com/Akhliskun/firefox-infra-changelog/commit/8d1b167b9f4135f4118b81db63640f336dd6cb86

**Comment by bccrisan** [comment]
After doing a lot of debugging all I can say is that the " useful_data = filter_commit_data(commit_data)" it's empty..

I also tried doing different combinations, like swapping, adding or removing different repositories and the result was different, sometimes the error doesn't appear right after the second iteration of the for loop in the github loop, it depends on the position of the 2nd repository that has the same team ..

**Comment by raduiman** [comment]
The error was from repositories.json. There are some repositories with wrong or not corresponding url, name and team.
e.g release-services is under mozilla-releng which is wrong. The correct team is mozilla

Fixed in PR #50
