### ISSUE TITLE
Create Github and Mercurial handler definitions outside the main function

### ISSUE THREAD

**Issue by bccrisan** [Akhliskun/firefox-infra-changelog#51]
Create separate GItHub and Mercurial handler definitions, outside the main function.

I would prefer a specific definition of each handler that has proper documentation.

The current definitions are buggy and are missing features.
Both functions should contain/do the following:
- a way of filtering data
- should write both `.md` and `.json` files for each repository.

**Comment by bccrisan** [comment]
Added in PR #75

**Comment by raduiman** [comment]
PR #79 implemented the HG MD generator.
All the functions are outside from the main part of the script.
We have a function for each of HG and GIT to filter the dates.
Both for GIT and for HG we have .json and .md files for each repositories.
Is something else to do on this issue? If not we can close it.

**Comment by raduiman** [comment]
It can be closed, the requirements was satisfied in #79
