### ISSUE TITLE
Main markdown table partially generated.

### ISSUE THREAD

**Issue by bccrisan** [Akhliskun/firefox-infra-changelog#87]
After the PR #85 the json files format for git repositories has been changed and introduces new issues regarding the generation of the main markdown table.

The issues is introduced by the first json element that now stores the last checked date.

Run the script
Check the main markdown table file.

**Actual Result**
Only the changes from the mercurial files are updated.

**Expected behavior**
The main markdown table should be updated with the latest changes on the git files and hg files.

**Additional context**
This appeared after structural modification of the git json files.

**Comment by mutterroland** [comment]
As the bug has been solved by @bccrisan and the PR has been merged, this can safely be closed.
