### ISSUE TITLE
Check hg commit message for " | " characters and add escape char

### ISSUE THREAD

**Issue by popadrianc** [Akhliskun/firefox-infra-changelog#91]
**Describe the bug**
https://github.com/Akhliskun/firefox-infra-changelog/blob/zfay_dev/hg_files/autoland.md
As shown in the link , at the 14 and 3 commits the table is broken, because the commit message contains the  char " | "

**Comment by Akhliskun** [comment]
PR mentioned above was merged.
closing the issue.
